<?php

/**
 * BaseConfigs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $value
 * 
 * @method string  getName()  Returns the current record's "name" value
 * @method string  getValue() Returns the current record's "value" value
 * @method Configs setName()  Sets the current record's "name" value
 * @method Configs setValue() Sets the current record's "value" value
 * 
 * @package    roLL
 * @subpackage model
 * @author     Piotr Cichocki
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfigs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('configs');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('value', 'string', 4095, array(
             'type' => 'string',
             'length' => 4095,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}