<?php

/**
 * BaseUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $login
 * @property string $password
 * @property string $name
 * @property string $email
 * @property string $type
 * 
 * @method string getLogin()    Returns the current record's "login" value
 * @method string getPassword() Returns the current record's "password" value
 * @method string getName()     Returns the current record's "name" value
 * @method string getEmail()    Returns the current record's "email" value
 * @method string getType()     Returns the current record's "type" value
 * @method Users  setLogin()    Sets the current record's "login" value
 * @method Users  setPassword() Sets the current record's "password" value
 * @method Users  setName()     Sets the current record's "name" value
 * @method Users  setEmail()    Sets the current record's "email" value
 * @method Users  setType()     Sets the current record's "type" value
 * 
 * @package    roLL
 * @subpackage model
 * @author     Piotr Cichocki
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users');
        $this->hasColumn('login', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 127,
             ));
        $this->hasColumn('type', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}