<?php

/**
 * BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property float $prize
 * @property string $regon
 * @property integer $month
 * @property Doctrine_Collection $Contracts
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method float               getPrize()       Returns the current record's "prize" value
 * @method string              getRegon()       Returns the current record's "regon" value
 * @method integer             getMonth()       Returns the current record's "month" value
 * @method Doctrine_Collection getContracts()   Returns the current record's "Contracts" collection
 * @method Product             setName()        Sets the current record's "name" value
 * @method Product             setDescription() Sets the current record's "description" value
 * @method Product             setPrize()       Sets the current record's "prize" value
 * @method Product             setRegon()       Sets the current record's "regon" value
 * @method Product             setMonth()       Sets the current record's "month" value
 * @method Product             setContracts()   Sets the current record's "Contracts" collection
 * 
 * @package    roLL
 * @subpackage model
 * @author     Piotr Cichocki
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4095, array(
             'type' => 'string',
             'length' => 4095,
             ));
        $this->hasColumn('prize', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('regon', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('month', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Contracts', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}