<?php

/**
 * BaseContracts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $client_id
 * @property integer $product_id
 * @property float $prize
 * @property integer $month
 * @property date $date_from
 * @property date $date_to
 * @property boolean $remind_pay
 * @property boolean $remind_end
 * @property Product $Product
 * @property Clients $Clients
 * 
 * @method string    getName()       Returns the current record's "name" value
 * @method integer   getClientId()   Returns the current record's "client_id" value
 * @method integer   getProductId()  Returns the current record's "product_id" value
 * @method float     getPrize()      Returns the current record's "prize" value
 * @method integer   getMonth()      Returns the current record's "month" value
 * @method date      getDateFrom()   Returns the current record's "date_from" value
 * @method date      getDateTo()     Returns the current record's "date_to" value
 * @method boolean   getRemindPay()  Returns the current record's "remind_pay" value
 * @method boolean   getRemindEnd()  Returns the current record's "remind_end" value
 * @method Product   getProduct()    Returns the current record's "Product" value
 * @method Clients   getClients()    Returns the current record's "Clients" value
 * @method Contracts setName()       Sets the current record's "name" value
 * @method Contracts setClientId()   Sets the current record's "client_id" value
 * @method Contracts setProductId()  Sets the current record's "product_id" value
 * @method Contracts setPrize()      Sets the current record's "prize" value
 * @method Contracts setMonth()      Sets the current record's "month" value
 * @method Contracts setDateFrom()   Sets the current record's "date_from" value
 * @method Contracts setDateTo()     Sets the current record's "date_to" value
 * @method Contracts setRemindPay()  Sets the current record's "remind_pay" value
 * @method Contracts setRemindEnd()  Sets the current record's "remind_end" value
 * @method Contracts setProduct()    Sets the current record's "Product" value
 * @method Contracts setClients()    Sets the current record's "Clients" value
 * 
 * @package    roLL
 * @subpackage model
 * @author     Piotr Cichocki
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContracts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contracts');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('prize', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('month', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date_from', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_to', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('remind_pay', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('remind_end', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Clients', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}