<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/07 19:33:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=127.0.0.1;dbname=roLL',
  'username' => 'roll',
  'password' => 'EbyzeJy-doFuh',
  'name' => 'doctrine',
)),);
