<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/03/13 11:44:15
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
);
