<?php

/**
 * Configs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    roLL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Configs extends BaseConfigs
{
	
	static function setConfig($name,$value){
		$conf = self::getRowByName('name', $name);
		if (count($conf)){
			$conf = $conf[0];
		}else{
			$conf = new Configs();
			$conf -> name = $name;
		}
		$conf -> value = $value;
		$conf -> save();
		
		return $conf->id;
		
	}
	
	static function getConfig($name){
		$conf = self::getRowByName('name', $name);
		if (count($conf)){
			return $conf[0] -> value;
		}
		
		return false;
		
	}
	
	
}
