<?php

/**
 * ContractsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContractsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContractsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contracts');
    }
}