<?php

/**
 * Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    roLL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Users extends BaseUsers
{
	
	static function authUser($login,$password){
		return self::getRowsFromArray( array('login'=> $login,'password'=>$password));
	}
	
	function getType(){
		$type = $this->_get('type');
		switch($type){
			case "admin":
				return 'administrator';
			case 'user':
				return "użytkownik";
			default:
				return "nieznany";
		}
	}
	
	
}
