# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: login, action: index }

# generic rules
# please, remove them by adding more specific rules
login:
  url: /login
  param: {module:login, action: index}

main:
  url: /main
  param: {module:main, action: index}
  
config:
  url: /config
  param: {module:config, action: config}  

config:
  url: /access
  param: {module:config, action: access}
  
config:
  url: /contract
  param: {module:contract, action: list}   

product:
  url: /product
  param: {module:product, action: list}
  
client:
  url: /client
  param: {module:client, action: list}  
  
 

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
