# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        roll
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [style.css,style_header.css,style_listy.css,style_panel.css,style_statystyki.css]

  javascripts:    [jquery-1.7.1.min.js,scripts.js]

  has_layout:     true
  layout:         layout
