<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/06 20:06:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=roLL',
  'username' => 'roll',
  'password' => 'EbyzeJy-doFuh',
  'name' => 'doctrine',
)),);
